#!/bin/bash

if [ -z "$ISL" ]; then
   echo "Error: need to set ISL env var to repo root to use commit-msg checker"
   exit 1
fi

#source the commit-msg-checker.sh script, which calls main py file
python "$ISL/git-hooks/commit-msg-checker.py" "$1"

