#!/bin/bash

exit_prog(){
    echo $1
    exit 1
}

CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
RELEASE_TAG="tmp_ci_leaderboard"

cd "$ISL"
cd docs/meta
python leaderboard.py || { exit_prog "Leaderboard generation failed"; }

cd ..
tar -czf custom_pages.tar.gz custom_pages

# make github temp release
gh release create "$RELEASE_TAG" --target "$CURRENT_BRANCH" -t Leaderboard -n "Leaderboard" -p || { exit_prog "Creation failed"; }
gh release upload "$RELEASE_TAG" custom_pages.tar.gz || { exit_prog "Upload failed"; }

# cleanup
rm custom_pages.tar.gz || { exit_prog "Cleanup failed"; }

exit 0
