---
version: "2"

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - git clone https://github.com/tmasthay/rich_tools.git
      - cd rich_tools
      - pip install -e .
      - cd ..
      - pip install -e .
      - sphinx-apidoc -o docs/source misfit_toys

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
