nx: 100
ny: 100
nt: 100
dx: 10.0
dy: 10.0
dt: 0.001
vp: [1000.0, 2000.0]
device: cuda

src:
  n_shots: 10
  src_per_shot: 1
  fst_src: 2
  d_src: 5
  src_depth: 2
  d_intra_shot: 1

rec:
  rec_per_shot: 50
  x_min: 100.0
  x_max: 800.0
  y_min: 100.0
  y_max: 800.0

amp:
  freq: 25.0
  peak_scale: 1.5

plot:
  v:
    name: vp.jpg
    title: $V_p$
    xlabel: $\lambda_{x}$
    ylabel: $\lambda_{y}$
    cmap: nipy_spectral
    imshow_kw:
      aspect: auto
