path: /home/tyler/anaconda3/envs/dw/data/marmousi/vp.pt

twolayer: True

nx: 250
ny: 600
nt: 300
dx: 4.0
dy: 4.0
dt: 0.004
vp: [1500.0, 2000.0]
device: cuda
accuracy: 8

src:
  n_shots: 1
  src_per_shot: 1
  fst_src: 120
  d_src: 20
  src_depth: 300
  d_intra_shot: 1

rec:
  padx: 10
  pady: 10
  x_min: 100.0
  x_max: 800.0
  y_min: 100.0
  y_max: 800.0

amp:
  freq: 25.0
  peak_scale: 1.5

plot:
  v:
    name: vp.jpg
    title: $V_p$
    xlabel: $Extent$ (m)
    ylabel: $Depth$ (m)
    cmap: nipy_spectral
    imshow_kw:
      aspect: auto

  out:
    name: out.gif
    title: Observed Data
    xlabel: Horizontal (m)
    ylabel: Depth (m)
    shape: [1, 1]
    figsize: [10, 10]
    duration: 100
    downsample: 1
    start: 30
    cut: 0
    imshow_kw:
      aspect: auto
      cmap: gray
