nx: 1000
ny: 1000
nt: 1000
dx: 1.0
dy: 1.0
dt: 0.004
vp: [1500.0, 2000.0]
device: cuda
accuracy: 8

src:
  n_shots: 10
  src_per_shot: 1
  fst_src: 2
  d_src: 5
  src_depth: 2
  d_intra_shot: 1

rec:
  rec_per_shot: 50
  x_min: 100.0
  x_max: 800.0
  y_min: 100.0
  y_max: 800.0

amp:
  freq: 2.0
  peak_scale: 1.5

plot:
  v:
    name: vp.jpg
    title: $V_p$
    xlabel: $Extent$ (m)
    ylabel: $Depth$ (m)
    cmap: nipy_spectral
    imshow_kw:
      aspect: auto

  out:
    name: out.gif
    title: Observed Data
    xlabel: Receiver Number
    ylabel: Time (s)
    cmap: nipy_spectral
    shape: [1, 1]
    figsize: [10, 10]
    duration: 100
    imshow_kw:
      aspect: auto
