runtime_func: ^^|misfit_toys.types|PickleUnaryFunction
kw:
  callback: ^^cwd|helpers|load_data
  delete_keys: null
  path: ${oc.env:CONDA_PREFIX}/data/marmousi/deepwave_example/shots16
  fields:
    obs_data: obs_data
    meta: metadata
    v_true: vp_true
    v_init: vp_init
    rec_loc_y: rec_loc_y
    src_amp_y: src_amp_y
    src_loc_y: src_loc_y
