__call__: "eval(lambda *args, **kw: [torch.optim.LBFGS, kw])"
args: []
kw:
  lr: 1.0
  max_iter: 20
  max_eval: null
  tolerance_grad: 1.0e-07
  tolerance_change: 1.0e-09
  history_size: 100
  line_search_fn: null
