runtime_func: ^^null|misfit_toys.workflows.tik.steps|taper_batch
kw:
  length: 0.3
  batch_size: 6
  scale: 1.0e+06
  verbose: true
  src_amp_y: self.runtime.data.src_amp_y


nonexist: checking_the_yaml_format_hook
