frame_callback:
  __plot__: ^^|misfit_toys.types|FlatPlotter
  kw:
    callback: ^^cwd|helpers.Plots|src_amp
    iter:
      none_dims: [1, 2]
      strides: [2, 1, 1]
    imshow:
      kw:
        aspect: auto
        cmap: seismic
      colorbar: true
      legend: false
