retrain: true
max_iters: 25

loss:
  chosen: tik
  tik:
    chosen: lin_reg_drop
    type: self.dep.train.loss.TikhonovLoss
    lin_reg_drop:
      func: self.dep.train.loss.lin_reg_drop
      args: []
      kw:
        scale: 1.0e-06
        _min: 1.0e-07
