__rt_callback__: ^^cwd|helpers|static_plots

imshow_defaults: &IMSHOW
  cmap: seismic
  aspect: auto

vp:
  imshow:
    <<: *IMSHOW
  transpose: true
  title: Velocity Model
  xlabel: Offset (m)
  ylabel: Depth (m)
  colorbar: true
