name: documentation

on:
  workflow_dispatch:
    inputs:
      leaderboard:
        description: "Leaderboard content"
        required: true

permissions:
  contents: write

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.leaderboard }}
