name: documentation

on:
  push:
    branches:
    - main
    - devel
    - feature/*
    tags-ignore:
    - tmp_ci_leaderboard

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # check-commit-msg:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     skip_e2e_tests: ${{ steps.check_commit_msg.outputs.skip_e2e_tests }}
  #   steps:
  #   - name: Check commit message
  #     id: check_commit_msg
  #     run: |
  #       if [[ "${{ github.event.head_commit.message }}" == *"[skip docs]"* ]]; then
  #         echo "::set-output name=skip_docs::true"
  #       else
  #         echo "::set-output name=skip_docs::false"
  #       fi

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3

    - name: Download tmp leaderboard release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $(type gh)
        echo $(gh --version)
        gh release download tmp_ci_leaderboard
        tar -xvf custom_pages.tar.gz
        mv custom_pages docs
        mkdir -p docs/_build/html
        cp -r docs/custom_pages/leaderboard docs/_build/html
        rm custom_pages.tar.gz

    - name: Install dependencies
      run: |
        pip install git+https://github.com/patrick-kidger/torchcubicspline.git
        pip install -e .
        pip install sphinx furo sphinx-autoapi sphinxcontrib-details-directive sphinx-togglebutton

    # - name: Set up GitHub CLI
    #   uses: actions/setup-gh-cli@v2

    # - name: Authenticate GitHub CLI
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: gh auth login --with-token


    - name: Sphinx build
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        force_orphan: true

    - name: Cleanup
      if: always()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete tmp_ci_leaderboard -y --cleanup-tag
