name: documentation

on: [push]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3

    - name: Download tmp leaderboard release and then delete it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $(type gh)
        echo $(gh --version)
        gh release download tmp_ci_leaderboard
        tar -xvf custom_pages.tar.gz
        mv custom_pages docs
        mkdir -p _build/html
        mv custom_pages/_leaderboard _build/html
        rm custom_pages.tar.gz
        gh release delete tmp_ci_leaderboard -y --cleanup-tag

    - name: Install dependencies
      run: |
        pip install git+https://github.com/patrick-kidger/torchcubicspline.git
        pip install -e .
        pip install sphinx furo sphinx-autoapi sphinxcontrib-details-directive

    # - name: Set up GitHub CLI
    #   uses: actions/setup-gh-cli@v2

    # - name: Authenticate GitHub CLI
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: gh auth login --with-token


    - name: Sphinx build
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        force_orphan: true
