---
name: GPU Validation Workflow

on:
  push:
    paths-ignore:
      - '**/hello.txt'  # Avoid infinite loop on automated commits

jobs:
  run_gpu_validation:
    runs-on: ubuntu-latest
    env:
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute SSH Command and Push Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            cd $ISL
            conda activate dw
            echo "Hello from Github at $(date)!" > hello.txt
            git add hello.txt
            git commit --amend --no-edit --no-verify
            git push --force-with-lease

      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Retrieve and Display Updated hello.txt
        run: |
          git fetch origin
          git checkout HEAD hello.txt
          echo "Updated contents of hello.txt:"
          cat hello.txt
