---
name: Python application test with pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel twine auditwheel
          pip install -r requirements.txt
          python setup.py install

      - name: Run pytest
        run: |
          pytest --cov=misfit_toys tests
