---
name: Python application test with pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # If you have other dependencies, install them here
          pip install -r requirements.txt
          pip install .

      - name: Run pytest
        run: |
          pytest
