---
name: GPU Validation Workflow

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  run_gpu_validation:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    env:
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      MY_PAT: ${{ secrets.MY_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute SSH Command and Push Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $ISL/.github/workflows/scripts/pytest
            ./validate_gpu.sh $MY_PAT
